# Generated by Django 5.0.6 on 2024-10-03 23:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('CO', 'Completed'), ('CA', 'Cancelled'), ('OH', 'On hold')], default='OH', max_length=5),
        ),
        migrations.AddField(
            model_name='projects',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
