# Generated by Django 5.0.6 on 2024-10-04 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engineers', '0003_engineers_created_at_engineers_updated_at'),
        ('projects', '0002_projects_created_at_projects_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectQuotations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engineer_total_amount', models.FloatField(default=0.0)),
                ('added_computation_value', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('engineers', models.ManyToManyField(to='engineers.engineers')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects')),
            ],
        ),
    ]
