# Generated by Django 5.0.6 on 2024-10-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessPartners', '0002_businesspartners_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartnerscontactpersonnel',
            name='contact_num',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
