# Generated by Django 5.0.6 on 2024-10-03 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engineers', '0003_engineers_created_at_engineers_updated_at'),
        ('projects', '0002_projects_created_at_projects_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Ac', 'Active'), ('In', 'Inactive'), ('Can', 'Cancelled'), ('Com', 'Completed'), ('On', 'On hold')], max_length=5)),
                ('duration', models.DurationField()),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineers.engineers')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects')),
            ],
        ),
    ]
