# Generated by Django 5.0.6 on 2024-10-03 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngineerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('FE', 'Frontend Dev'), ('BE', 'Backend Dev'), ('FS', 'Full Stack Dev'), ('DO', 'Dev Ops Engineer'), ('CE', 'Cloud Engineer')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Engineers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contact_num', models.CharField(unique=True)),
                ('engineer_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineers.engineertype')),
            ],
        ),
    ]
