# Generated by Django 5.0.6 on 2024-10-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineers',
            name='salary',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
