# Generated by Django 5.0.6 on 2024-10-03 23:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0002_engineers_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engineers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
