# Generated by Django 5.0.6 on 2024-10-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0003_engineers_created_at_engineers_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineers',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='engineers',
            name='contact_num',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
